export const routes = {
	home: '/',
	login: '/login',
	accountManagement: '/accountManagement',
	agentProfileManagement: '/accountManagement/agentProfileManagement',
	changePassword: '/changePassword',
	createStreamerEvent: '/promotion/createStreamerEvent',
	promotionApplication: '/promotion/application',
	manualPointGiveaway: '/promotion/manualPointGiveaway',
	uploadImage: '/uploadImage',
};
export const apiRoutes = {
	login: '/Login',
	updatePassword: '/Account/UpdatePassword',
	getCreateGameEventInfo: '/Event/GetCreateGameEventInfo',
	searchEventList: '/Event/SearchGameEventList',
	getEventDetail: '/Event/GetEventDetail',
	duplicateEvent: '/Event/duplicateEvent',
	createGameEvent: '/Event/createGameEvent',
	getCountryList: '/Event/GetEventCountries',
	getGameCodeList: '/Event/GetCreateGameCodes',
	downLoad: '/api/download',
	searchRewardList: '/Reward/SearchDistributionList',
	updateProfileImage: '/Account/UpdateProfileImage',
	getProfileInfo: '/Account/GetAccountProfile',
	getDistributionDetail: '/Reward/GetDistributionDetail',
	createDistribution: '/Reward/CreateDistribution',
};
