apiVersion: apps/v1
kind: Deployment
metadata:
  name: utopia-agent-f2e
  labels:
    service: utopia-agent-f2e-svc
  namespace: utopia-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utopia-agent-f2e
      environment: prod
      tier: frontend
      release: stable
      version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: utopia-agent-f2e
        environment: prod
        tier: frontend
        release: stable
        version: v1
    spec:
      containers:
        - name: utopia-agent-f2e
          image: {{IMAGE}}
          imagePullPolicy: IfNotPresent
          command: ["npm", "run", "start"]
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /favicon.ico
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /favicon.ico
              port: 3000
            periodSeconds: 10
            initialDelaySeconds: 20
          resources:
            requests:
              memory: "300Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: utopia-agent-f2e-svc
  namespace: utopia-prod
  labels:
    app: utopia-agent-f2e
    environment: prod
    tier: frontend
    release: stable
    version: v1
spec:
  type: ClusterIP
  selector:
    app: utopia-agent-f2e
  ports:
    - name: http
      port: 80
      targetPort: 3000
